import type { ArticleFull, ArticleMeta } from "@/lib/types/strapi";

const stories: ArticleFull[] = [
  {
    id: -101,
    documentId: "rss-nepal-dairy-farmers",
    title: "Lawmakers urge timely payments to dairy farmers",
    slug: "lawmakers-urge-timely-payments-to-dairy-farmers",
    excerpt: "Members of Parliament raised dairy payments, road safety, disaster risks and consumer protection during Zero Hour.",
    content: "Members of Parliament have called for timely payments to dairy farmers while raising concerns about road safety, disaster risks, health services and consumer protection.\n\nThis brief is based on reporting by **Rastriya Samachar Samiti (RSS)**. [Read the source report](https://radionepalonline.com/en/2026/07/06/432220.html).",
    coverUrl: "",
    coverAlt: "",
    readingTime: 2,
    featured: false,
    authorName: "Rastriya Samachar Samiti (RSS)",
    authorSlug: "rss",
    authorBio: "Nepal's national news agency.",
    authorAvatarUrl: null,
    categoryName: "Nepal",
    categorySlug: "nepal",
    tags: [{ name: "Nepal", slug: "nepal" }],
    publishedAt: "2026-07-06T06:00:00.000Z",
    seo: null,
  },
  {
    id: -102,
    documentId: "rss-nepal-ai-summit",
    title: "Nepali students join AI for Good Global Summit",
    slug: "nepali-students-join-ai-for-good-global-summit",
    excerpt: "A Nepali student team is participating in the Robotics for Good Youth Challenge at the global summit in Switzerland.",
    content: "A team of Nepali students is participating in the Robotics for Good Youth Challenge at the AI for Good Global Summit in Switzerland. The event is organised by the International Telecommunication Union.\n\nThis brief is based on reporting by **Rastriya Samachar Samiti (RSS)**. [Read the source report](https://radionepalonline.com/en/2026/07/04/432111.html).",
    coverUrl: "",
    coverAlt: "",
    readingTime: 2,
    featured: false,
    authorName: "Rastriya Samachar Samiti (RSS)",
    authorSlug: "rss",
    authorBio: "Nepal's national news agency.",
    authorAvatarUrl: null,
    categoryName: "Nepal",
    categorySlug: "nepal",
    tags: [{ name: "Technology", slug: "technology" }],
    publishedAt: "2026-07-04T06:00:00.000Z",
    seo: null,
  },
  {
    id: -201,
    documentId: "rss-world-us-iran-groups",
    title: "US and Iran form working groups in Switzerland",
    slug: "us-and-iran-form-working-groups-in-switzerland",
    excerpt: "Diplomatic talks moved into working groups as mediators continued efforts to narrow differences between Washington and Tehran.",
    content: "The United States and Iran moved diplomatic discussions into working groups in Switzerland as mediators continued efforts to narrow differences and reduce regional tensions.\n\nThis is a concise brief from the **RSS international news service**. [See the international source desk](https://radionepalonline.com/en/topics/international).",
    coverUrl: "",
    coverAlt: "",
    readingTime: 2,
    featured: false,
    authorName: "RSS International Desk",
    authorSlug: "rss",
    authorBio: "International reporting distributed through the RSS news-agency network.",
    authorAvatarUrl: null,
    categoryName: "International",
    categorySlug: "international",
    tags: [{ name: "Diplomacy", slug: "diplomacy" }],
    publishedAt: "2026-06-23T06:00:00.000Z",
    seo: null,
  },
  {
    id: -202,
    documentId: "rss-world-conflict-violence",
    title: "EU and UN call for action on conflict-related sexual violence",
    slug: "eu-un-call-for-action-on-conflict-related-sexual-violence",
    excerpt: "International institutions called for stronger accountability and protection for people living in conflict zones.",
    content: "The European Union and United Nations called for stronger international action, accountability and protection in response to sexual violence in conflict zones.\n\nThis is a concise brief from the **RSS international news service**. [See the international source desk](https://radionepalonline.com/en/topics/international).",
    coverUrl: "",
    coverAlt: "",
    readingTime: 2,
    featured: false,
    authorName: "RSS International Desk",
    authorSlug: "rss",
    authorBio: "International reporting distributed through the RSS news-agency network.",
    authorAvatarUrl: null,
    categoryName: "International",
    categorySlug: "international",
    tags: [{ name: "World", slug: "world" }],
    publishedAt: "2026-06-19T06:00:00.000Z",
    seo: null,
  },
  {
    id: -301,
    documentId: "daily-governance-delivery-unit",
    title: "PM's Office moves to create a delivery unit",
    slug: "pm-office-moves-to-create-delivery-unit",
    excerpt: "The proposed unit would monitor national commitments and coordinate implementation across ministries.",
    content: "The Prime Minister's Office is preparing a delivery unit to track the government's 18-point national commitments and coordinate work across ministries.\n\n## Why it matters\n\nNepal's policy problem is often implementation rather than announcement. A central tracking unit could make delays and institutional bottlenecks easier to identify.\n\n## Driving the news\n\n- The unit is expected to monitor delivery across ministries and agencies.\n- The model draws on policy-delivery systems used in countries including the UK, Malaysia and Rwanda.\n\n## What to watch\n\nIts impact will depend on measurable targets, public reporting and whether ministries respond to the unit's findings.\n\n**Source:** [Onlinekhabar reporting, July 12, 2026](https://www.onlinekhabar.com/2026/07/1973774/balen-forming-pm-delivery-unit).",
    coverUrl: "", coverAlt: "", readingTime: 2, featured: true,
    authorName: "KUTNITI News Desk", authorSlug: "kutniti-news-desk", authorBio: "KUTNITI's source-backed daily news desk.", authorAvatarUrl: null,
    categoryName: "Politics", categorySlug: "politics", tags: [{ name: "Governance", slug: "governance" }],
    publishedAt: "2026-07-12T05:05:00.000Z", seo: null,
  },
  {
    id: -302,
    documentId: "daily-passport-accountability",
    title: "Parliamentary panel to examine e-passport printing dispute",
    slug: "parliamentary-panel-to-examine-e-passport-printing-dispute",
    excerpt: "The Public Accounts Committee has called officials from the foreign ministry and passport department for answers.",
    content: "Parliament's Public Accounts Committee plans to discuss questions surrounding Nepal's electronic-passport printing process.\n\n## Why it matters\n\nPassport procurement touches public money, national security and the reliability of a critical citizen service.\n\n## Driving the news\n\n- The committee has invited officials from the Ministry of Foreign Affairs and Department of Passports.\n- Lawmakers have raised questions around a dispute valued at roughly Rs 10.13 billion.\n\n## What to watch\n\nThe meeting is expected to clarify the procurement record; an invitation to explain is not itself a finding of wrongdoing.\n\n**Source:** [Onlinekhabar reporting, July 12, 2026](https://www.onlinekhabar.com/2026/07/1973807/parliaments-public-accounts-committee-to-discuss-e-passport-printing-issue).",
    coverUrl: "", coverAlt: "", readingTime: 2, featured: false,
    authorName: "KUTNITI News Desk", authorSlug: "kutniti-news-desk", authorBio: "KUTNITI's source-backed daily news desk.", authorAvatarUrl: null,
    categoryName: "Politics", categorySlug: "politics", tags: [{ name: "Accountability", slug: "accountability" }],
    publishedAt: "2026-07-12T06:08:00.000Z", seo: null,
  },
  {
    id: -303,
    documentId: "daily-nepse-six-month-low",
    title: "NEPSE falls to its lowest level in six months",
    slug: "nepse-falls-to-lowest-level-in-six-months",
    excerpt: "Recent policy announcements have yet to revive investor confidence in Nepal's share market.",
    content: "Nepal's benchmark share index has slipped to its lowest point in six months despite policy measures intended to support market confidence.\n\n## Why it matters\n\nA weak market can signal caution about liquidity, earnings and the credibility of policy support—not simply short-term trading sentiment.\n\n## The big picture\n\nThe budget made capital-gains tax the final tax for investors, but the market response has remained subdued.\n\n## What to watch\n\nTurnover, banking liquidity and the implementation of announced reforms will matter more than fresh promises.\n\n**Source:** [Onlinekhabar reporting, July 12, 2026](https://www.onlinekhabar.com/2026/07/1973792/even-policy-announcements-failed-to-restore-stock-market-enthusiasm-nepse-at-6-month-low).",
    coverUrl: "", coverAlt: "", readingTime: 2, featured: false,
    authorName: "KUTNITI News Desk", authorSlug: "kutniti-news-desk", authorBio: "KUTNITI's source-backed daily news desk.", authorAvatarUrl: null,
    categoryName: "Economy", categorySlug: "economy", tags: [{ name: "NEPSE", slug: "nepse" }],
    publishedAt: "2026-07-12T06:15:00.000Z", seo: null,
  },
  {
    id: -304,
    documentId: "daily-manpower-enforcement",
    title: "159 manpower companies face action over Indian airport departures",
    slug: "159-manpower-companies-face-action-over-indian-airport-departures",
    excerpt: "Labour authorities say the agencies sent workers through Indian airports without required approval.",
    content: "The Department of Foreign Employment has acted against 159 manpower companies accused of sending Nepali workers through Indian airports without prior approval.\n\n## Why it matters\n\nUnrecorded travel routes can weaken worker protection, complicate rescue efforts and make recruitment practices harder to audit.\n\n## By the numbers\n\n- 159 companies were warned over airport use.\n- Hundreds of other agencies were told to submit missing travel details.\n- Eight repeat offenders received Rs 50,000 fines, according to the department.\n\n## What to watch\n\nAuthorities have warned that repeated violations could lead to stronger enforcement.\n\n**Source:** [Onlinekhabar reporting, July 12, 2026](https://www.onlinekhabar.com/2026/07/1973814/159-manpower-companies-taking-workers-out-of-indian-airports-under-action).",
    coverUrl: "", coverAlt: "", readingTime: 2, featured: false,
    authorName: "KUTNITI News Desk", authorSlug: "kutniti-news-desk", authorBio: "KUTNITI's source-backed daily news desk.", authorAvatarUrl: null,
    categoryName: "Business", categorySlug: "business", tags: [{ name: "Labour", slug: "labour" }],
    publishedAt: "2026-07-12T06:02:00.000Z", seo: null,
  },
  {
    id: -305,
    documentId: "daily-farmer-pension",
    title: "Government commits to a contribution-based farmer pension",
    slug: "government-commits-to-contribution-based-farmer-pension",
    excerpt: "The national commitment also links farmer IDs to subsidies, credit, insurance and social protection.",
    content: "The government has included a contribution-based farmer pension in its national commitments, alongside farmer identification and targeted support.\n\n## Why it matters\n\nAgricultural support often misses genuine small farmers. Linking benefits to a credible identification system could improve targeting—but only if registration is accessible and transparent.\n\n## Driving the news\n\nThe commitment also mentions credit cards, insurance, concessional loans, irrigation expansion and support for a domestic fertiliser plant.\n\n## What to watch\n\nThe next test is whether the pledge receives a funded programme, eligibility rules and an implementation timeline.\n\n**Source:** [Onlinekhabar reporting, July 12, 2026](https://www.onlinekhabar.com/2026/07/1973823/governments-commitment-to-provide-pension-to-farmers).",
    coverUrl: "", coverAlt: "", readingTime: 2, featured: false,
    authorName: "KUTNITI News Desk", authorSlug: "kutniti-news-desk", authorBio: "KUTNITI's source-backed daily news desk.", authorAvatarUrl: null,
    categoryName: "Nepal", categorySlug: "nepal", tags: [{ name: "Agriculture", slug: "agriculture" }],
    publishedAt: "2026-07-12T06:16:00.000Z", seo: null,
  },
  {
    id: -306,
    documentId: "daily-u19-women-cricket",
    title: "Nepal moves closer to U-19 Women's Premier Cup quarterfinals",
    slug: "nepal-nears-u19-womens-premier-cup-quarterfinals",
    excerpt: "A second consecutive victory has strengthened Nepal's position in the tournament.",
    content: "Nepal's U-19 women's cricket team moved closer to the Premier Cup quarterfinals after recording a second straight win.\n\n## Why it matters\n\nConsistent age-group results deepen Nepal's women's cricket pathway and give emerging players more high-pressure international experience.\n\n## What to watch\n\nThe remaining group result will determine qualification and Nepal's likely quarterfinal matchup.\n\n**Source:** [Onlinekhabar Sports, July 12, 2026](https://www.onlinekhabar.com/2026/07/1973767/u-19-womens-premier-cup-nepal-nears-quarterfinals-with-second-consecutive-win).",
    coverUrl: "", coverAlt: "", readingTime: 1, featured: false,
    authorName: "KUTNITI News Desk", authorSlug: "kutniti-news-desk", authorBio: "KUTNITI's source-backed daily news desk.", authorAvatarUrl: null,
    categoryName: "Sports", categorySlug: "sports", tags: [{ name: "Cricket", slug: "cricket" }],
    publishedAt: "2026-07-12T05:40:00.000Z", seo: null,
  },
  {
    id: -400,
    documentId: "world-cup-2026-final-four",
    title: "Four teams, one trophy: What could decide the World Cup semifinals",
    slug: "world-cup-2026-semifinalists-strengths-weaknesses-key-players",
    excerpt: "Spain want the ball, France want the space, Argentina trust their nerve and England keep finding a way back. Only two can reach the final.",
    content: "The World Cup is down to four familiar heavyweights, but they have arrived here in very different ways. France meet Spain on July 14. A day later, Argentina face England.\n\n## Spain: Control is their comfort zone\n\n**Why they can win:** With Rodri setting the rhythm, Spain can keep the ball for long stretches and squeeze opponents with a sharp counter-press. They went five straight games without conceding before Belgium finally broke through.\n\n**Where they can be hurt:** All that control does not always lead to enough clear chances. Belgium stayed alive until the closing minutes, and Spain still lack the kind of penalty-box finisher who turns half a chance into a goal.\n\n**Who has stepped up:** Lamine Yamal keeps pulling defenders toward the right touchline. Mikel Oyarzabal has brought goals, while Mikel Merino has become the man for late moments — including the winner against Belgium. Rodri is still the player who makes everything feel calm.\n\nSpain reached the semifinal with a 2-1 win over Belgium.\n\n## France: One burst can change everything\n\n**Why they can win:** France do not need to dominate every minute. They can wait, defend space and then explode forward. Kylian Mbappé has eight goals and three assists, and their quick centre-backs give the rest of the team freedom to attack.\n\n**Where they can be hurt:** When both wingers stay high, the midfield can open up. France have also had spells when they protect a lead too early and invite pressure they do not need.\n\n**Who has stepped up:** Mbappé is the obvious danger, especially when he can run behind a high line. Ousmane Dembélé can unsettle a defence on either side, while William Saliba has been the steady figure at the back.\n\nFrance booked their place with a convincing 2-0 win over Morocco.\n\n## Argentina: They are comfortable in the chaos\n\n**Why they can win:** Argentina have lived through almost every kind of knockout night. They know when to slow a game down, when to fight and when to add another attacker. That experience matters when legs get heavy and the match becomes emotional.\n\n**Where they can be hurt:** The holders have made life difficult for themselves. Even against 10-man Switzerland, they needed extra time. Their passing can become slow when opponents close the middle and wait for Messi.\n\n**Who has stepped up:** Lionel Messi is level with Mbappé on eight goals. Julián Álvarez produced the breakthrough against Switzerland, Lautaro Martínez finished the job and Emiliano Martínez continues to give the team confidence in tense moments.\n\nArgentina eventually beat Switzerland 3-1 after extra time.\n\n## England: They keep answering the pressure\n\n**Why they can win:** England have power, height and players who enjoy the biggest moments. Jude Bellingham can drive through midfield, while Harry Kane can score, drop deep and bring runners into the game.\n\n**Where they can be hurt:** They have been slow out of the blocks. Congo DR led them until the 75th minute, and Norway scored first in the quarterfinal. Against Argentina, another hesitant start could be costly.\n\n**Who has stepped up:** Bellingham scored twice in the comeback against Norway and now has six goals. Kane also has six. Bukayo Saka gives England width, and Declan Rice will have the difficult job of protecting the spaces Messi likes to use.\n\nEngland came from behind to beat Norway 2-1.\n\n## Two very different semifinals\n\n**France vs Spain:** Spain will try to keep France away from the ball. France will wait for the moment Spain's full-backs leave space behind them. Rodri's ability to stop those breaks could decide the match.\n\n**Argentina vs England:** England have younger legs and more aerial power. Argentina have deeper knockout experience and Messi between the lines. The midfield contest around Bellingham, Rice and Argentina's central players should tell us who controls the night.\n\n## Four questions before kickoff\n\n- Can Spain keep Mbappé away from open space?\n- Can Argentina give Messi freedom without losing the midfield?\n- Can Bellingham or Kane catch Golden Boot leaders Messi and Mbappé?\n- Will France stay balanced when Spain overload the wings?\n\n**Sources:** [FIFA tournament schedule](https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026/articles/match-schedule-fixtures-results-teams-stadiums), [AP: Argentina 3-1 Switzerland](https://apnews.com/article/d47ccb4ac5b3af67eca1f82228155174), [AP: England 2-1 Norway](https://apnews.com/article/f246f138c3a8563cb5a0e3f4037e930a), [AP: Spain 2-1 Belgium](https://apnews.com/article/780243a17571b6b2b26074b66feec90a), [FIFA: France 2-0 Morocco](https://www.fifa.com/fr/articles/resume-temps-forts-france-maroc-quarts).",
    coverUrl: "/world-cup-2026-semifinalists.png",
    coverAlt: "Four World Cup semifinalists approaching the trophy",
    readingTime: 7,
    featured: true,
    authorName: "Arjun Neupane",
    authorSlug: "arjun-neupane",
    authorBio: "Sports writer and contributor at KUTNITI.",
    authorAvatarUrl: null,
    categoryName: "Sports",
    categorySlug: "sports",
    tags: [{ name: "World Cup 2026", slug: "world-cup-2026" }],
    publishedAt: "2026-07-12T12:30:00.000Z",
    seo: null,
  },
];

export const rssNews: ArticleMeta[] = [...stories].sort(
  (a, b) => new Date(b.publishedAt).getTime() - new Date(a.publishedAt).getTime()
);
export const getRssNewsByCategory = (slug: string) => rssNews.filter((story) => story.categorySlug === slug);
export const getRssNewsBySlug = (slug: string) => stories.find((story) => story.slug === slug);

